language: objective-c
osx_image: xcode8
before_install:
  - gem install scan --no-doc
script:
  - echo $SIMULATOR_ID
  - open -b com.apple.iphonesimulator --args -CurrentDeviceUDID $SIMULATOR_ID
  - set -o pipefail
  - scan
  # - pod lib lint
